sudo: required
services:
    - docker

before_install:
    - docker build -t jdpenuliar/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jdpenuliar/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-325600605545"
    bucket_path: "deocker-react" #will be the same as app name
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

# DockerReact-env.eba-ywinxf22.us-east-1.elasticbeanstalk.com 